<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="YP1002465LT" ignored="0" name="order" tests="1" failures="1" timestamp="23 Aug 2018 12:23:08 GMT" time="8.298" errors="0">
  <testcase name="@AfterMethod afterMethod" time="0.001" classname="testNgExample.Testcase1">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at testNgExample.Testcase1.afterMethod(Testcase1.java:36)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase name="f" time="0.014" classname="testNgExample.Testcase1">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at testNgExample.Testcase1.f(Testcase1.java:19)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- f -->
</testsuite> <!-- order -->
